workflows:
  ios-release-no-shorebird:
    name: IOS Release (No Shorebird)

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter pub get
      - flutter clean

      # Build pour iPhone sans signature Apple
      - flutter build ios --release --no-codesign

      # Création du dossier Payload
      - mkdir -p build/ios/iphoneos/Payload

      # Copie de l'application
      - cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      # Création du fichier .ipa
      - cd build/ios/iphoneos && zip -r Runner.ipa Payload

    artifacts:
      - build/ios/iphoneos/Runner.ipa
